# Quarkus application configuration
# Quarkus REST Client configuration for CatalogService
# Override with CATALOG_ENDPOINT env var or -DCATALOG_ENDPOINT=...
quarkus.rest-client."com.demo.service.CatalogService".url=${CATALOG_ENDPOINT:http://catalog-service}

# Quarkus HTTP configuration
quarkus.http.cors.origins=*
