# Quarkus configuration
quarkus.application.name=coolstore-cart
quarkus.http.port=8080
quarkus.smallrye-health.enabled=true

# Catalog service REST client
quarkus.rest-client."com.demo.service.CatalogService".url=${CATALOG_ENDPOINT:http://localhost:8081}
