# Quarkus configuration
quarkus.application.name=coolstore-cart
quarkus.http.port=8080
quarkus.smallrye-health.enabled=true

# Catalog service REST client configuration
quarkus.rest-client.catalogService.url=${CATALOG_ENDPOINT:http://127.0.0.1:8081}
